/**
 * @fileoverview Exact runtime named exports promised by each public JavaScript
 * subpath. Contract tests compare both source entry points and the installed npm
 * tarball against these names so a barrel edit cannot silently add or remove
 * public API. After an intentional barrel change, re-derive the manifest with
 * `bun run scripts/public-api-contract-update.ts`.
 * @module scripts/public-api-contract
 */

/** Exact runtime named exports promised by each public JavaScript subpath. */
export const PUBLIC_RUNTIME_EXPORTS = {
  '.': [
    'APP_RESOURCE_MIME_TYPE',
    'InputRequiredSignal',
    'appResource',
    'appTool',
    'completable',
    'createApp',
    'createFail',
    'createRecoveryFor',
    'disabledTool',
    'headerParam',
    'inputRequired',
    'isCompletable',
    'isInputRequiredSignal',
    'prompt',
    'resource',
    'tool',
    'validateDefinitions',
    'z',
  ],
  './worker': ['createWorkerHandler'],
  './tools': ['disabledTool', 'headerParam', 'tool'],
  './resources': ['resource'],
  './prompts': ['prompt'],
  './errors': [
    'ErrorSchema',
    'JsonRpcErrorCode',
    'McpError',
    'configurationError',
    'conflict',
    'databaseError',
    'forbidden',
    'internalError',
    'invalidParams',
    'invalidRequest',
    'notFound',
    'rateLimited',
    'serializationError',
    'serviceUnavailable',
    'timeout',
    'unauthorized',
    'validationError',
  ],
  './config': [
    'ConfigSchema',
    'FRAMEWORK_NAME',
    'FRAMEWORK_VERSION',
    'config',
    'parseConfig',
    'parseEnvConfig',
    'resetConfig',
  ],
  './auth': ['checkScopes'],
  './storage': ['StorageService'],
  './storage/types': [],
  './canvas': [
    'ALLOWED_PLAN_OPERATORS',
    'ALLOWED_STATEMENT_TYPES',
    'CANVAS_IDENTIFIER_REGEX',
    'CanvasInstance',
    'CanvasRegistry',
    'DEFAULT_CANVAS_REGISTRY_OPTIONS',
    'DENIED_TABLE_FUNCTIONS',
    'DataCanvas',
    'DuckdbProvider',
    'SQL_GATE_REASONS',
    'assertNoDeniedFunctions',
    'assertNoSystemCatalogs',
    'assertReadOnlyQuery',
    'assertValidIdentifier',
    'collectDisallowedOperators',
    'collectPlanViolations',
    'createCanvasService',
    'inferSchemaFromRows',
    'quoteIdentifier',
    'spillover',
  ],
  './mirror': [
    'DEFAULT_FTS_TOKENIZER',
    'buildSchemaSql',
    'defineMirror',
    'openSqliteHandle',
    'runSync',
    'sqliteMirrorStore',
    'validateSchemaSpec',
  ],
  './utils': [
    'ATTR_CODE_FUNCTION_NAME',
    'ATTR_CODE_NAMESPACE',
    'ATTR_GEN_AI_REQUEST_MAX_TOKENS',
    'ATTR_GEN_AI_REQUEST_MODEL',
    'ATTR_GEN_AI_REQUEST_STREAMING',
    'ATTR_GEN_AI_REQUEST_TEMPERATURE',
    'ATTR_GEN_AI_REQUEST_TOP_P',
    'ATTR_GEN_AI_RESPONSE_MODEL',
    'ATTR_GEN_AI_SYSTEM',
    'ATTR_GEN_AI_TOKEN_TYPE',
    'ATTR_GEN_AI_USAGE_INPUT_TOKENS',
    'ATTR_GEN_AI_USAGE_OUTPUT_TOKENS',
    'ATTR_GEN_AI_USAGE_TOTAL_TOKENS',
    'ATTR_MCP_AUTH_FAILURE_REASON',
    'ATTR_MCP_AUTH_METHOD',
    'ATTR_MCP_AUTH_OUTCOME',
    'ATTR_MCP_AUTH_SCOPES',
    'ATTR_MCP_AUTH_SUBJECT',
    'ATTR_MCP_CLIENT_ID',
    'ATTR_MCP_ERROR_CLASSIFIED_CODE',
    'ATTR_MCP_GRAPH_DURATION_MS',
    'ATTR_MCP_GRAPH_OPERATION',
    'ATTR_MCP_GRAPH_SUCCESS',
    'ATTR_MCP_RESOURCE_DURATION_MS',
    'ATTR_MCP_RESOURCE_ERROR_CODE',
    'ATTR_MCP_RESOURCE_MIME_TYPE',
    'ATTR_MCP_RESOURCE_SIZE_BYTES',
    'ATTR_MCP_RESOURCE_SUCCESS',
    'ATTR_MCP_RESOURCE_URI',
    'ATTR_MCP_SESSION_EVENT',
    'ATTR_MCP_SPEECH_DURATION_MS',
    'ATTR_MCP_SPEECH_INPUT_BYTES',
    'ATTR_MCP_SPEECH_OPERATION',
    'ATTR_MCP_SPEECH_OUTPUT_BYTES',
    'ATTR_MCP_SPEECH_PROVIDER',
    'ATTR_MCP_SPEECH_SUCCESS',
    'ATTR_MCP_STORAGE_DURATION_MS',
    'ATTR_MCP_STORAGE_KEY_COUNT',
    'ATTR_MCP_STORAGE_OPERATION',
    'ATTR_MCP_STORAGE_SUCCESS',
    'ATTR_MCP_TENANT_ID',
    'ATTR_MCP_TOOL_BATCH_FAILED',
    'ATTR_MCP_TOOL_BATCH_SUCCEEDED',
    'ATTR_MCP_TOOL_DURATION_MS',
    'ATTR_MCP_TOOL_ERROR_CATEGORY',
    'ATTR_MCP_TOOL_ERROR_CODE',
    'ATTR_MCP_TOOL_INPUT_BYTES',
    'ATTR_MCP_TOOL_NAME',
    'ATTR_MCP_TOOL_OUTPUT_BYTES',
    'ATTR_MCP_TOOL_PARTIAL_SUCCESS',
    'ATTR_MCP_TOOL_SUCCESS',
    'Allow',
    'CsvParser',
    'DEFAULT_BINARY_PARSER_MAX_BYTES',
    'DEFAULT_OUTLINE_BUDGET_BYTES',
    'DEFAULT_PAGINATION_CONFIG',
    'DEFAULT_TEXT_PARSER_MAX_BYTES',
    'DiffFormatter',
    'ErrorHandler',
    'FrontmatterParser',
    'HtmlExtractor',
    'IdGenerator',
    'JsonParser',
    'Logger',
    'MarkdownBuilder',
    'OUTLINE_VARIANT',
    'PdfParser',
    'RateLimiter',
    'SafeHtml',
    'Sanitization',
    'SchedulerService',
    'TableFormatter',
    'TreeFormatter',
    'XmlParser',
    'YamlParser',
    'arrayBufferToBase64',
    'base64ToString',
    'buildTraceparent',
    'countChatTokens',
    'countTokens',
    'createContextWithParentTrace',
    'createCounter',
    'createHistogram',
    'createUpDownCounter',
    'csvParser',
    'dateParser',
    'decodeCursor',
    'diffFormatter',
    'encodeCursor',
    'escapeHtml',
    'extractCursor',
    'extractTraceparent',
    'failureEntrySchema',
    'fetchWithTimeout',
    'formatOutline',
    'frontmatterParser',
    'generateRequestContextId',
    'generateUUID',
    'getMeter',
    'html',
    'htmlExtractor',
    'httpErrorFromResponse',
    'httpStatusToErrorCode',
    'idGenerator',
    'initializeOpenTelemetry',
    'injectCurrentContextInto',
    'isErrorWithCode',
    'isRecord',
    'jsonParser',
    'logger',
    'markdown',
    'outlineOnOverflow',
    'paginateArray',
    'parseDateString',
    'parseDateStringDetailed',
    'partialResult',
    'partialResultSchema',
    'pdfParser',
    'requestContextService',
    'runDetached',
    'runInContext',
    'runtimeCaps',
    'sanitization',
    'sanitizeInputForLogging',
    'schedulerService',
    'sdk',
    'selectSections',
    'shutdownOpenTelemetry',
    'stringToBase64',
    'tableFormatter',
    'thinkBlockRegex',
    'treeFormatter',
    'unsafeRaw',
    'withExtra',
    'withRetry',
    'withSpan',
    'xmlParser',
    'yamlParser',
  ],
  './services': [
    'ElevenLabsProvider',
    'GraphService',
    'OpenRouterProvider',
    'SpeechService',
    'WhisperProvider',
    'createSpeechProvider',
    'supportsSTT',
    'supportsTTS',
  ],
  './linter': ['validateDefinitions'],
  './testing': [
    'createFetchMock',
    'createInMemoryStorage',
    'createMockContext',
    'createMockLogger',
    'createMockSession',
    'expectInputRequired',
    'getContentBlocks',
    'getEnrichment',
    'runToolContract',
  ],
  './testing/fuzz': [
    'ADVERSARIAL_STRINGS',
    'adversarialArbitrary',
    'adversarialObjectArbitrary',
    'fuzzPrompt',
    'fuzzResource',
    'fuzzTool',
    'loadFc',
    'zodToArbitrary',
  ],
  './testing/vitest': [
    'createFetchMock',
    'createInMemoryStorage',
    'createMockContext',
    'createMockSession',
    'mcpTest',
    'runToolContract',
    'toolContractSuite',
  ],
} as const satisfies Record<string, readonly string[]>;

/** A public JavaScript subpath, keyed as it appears in `package.json` `exports`. */
export type PublicRuntimeSubpath = keyof typeof PUBLIC_RUNTIME_EXPORTS;
